### ISSUE TITLE
Now i got overheated people xD

### ISSUE THREAD

**Issue by Curse187** [SimonTheCoder/rise_to_ruins_trainer#1]
Hey Simon,

i tested the "Super Villager" feature. It didn't wend very well. Now all of my villager are SUPER overheated. xD

i got the last InDevVersion.

I fixed it in the save file.

Greetings
Curse187

**Comment by SimonTheCoder** [comment]
> Hey Simon,
> 
> i tested the "Super Villager" feature. It didn't wend very well. Now all of my villager are SUPER overheated. xD
> 
> i got the last InDevVersion.
> 
> I fixed it in the save file.
> 
> Greetings
> Curse187

Hi,

Sorry for the trouble.
It seems the Field ID of speed is changed in the last version of game.
I'll see if it can be fixed.
Thanks a lot.

**Comment by salsalplz** [comment]
Hello Simon

do you plan on adding more features to this trainer?
Also if you do plan on supporting this game with said trainer, id like to donate some towards you :)
for the work you have put in so far.

Regards sal.

**Comment by SimonTheCoder** [comment]
> Hey Simon,
> 
> i tested the "Super Villager" feature. It didn't wend very well. Now all of my villager are SUPER overheated. xD
> 
> i got the last InDevVersion.
> 
> I fixed it in the save file.
> 
> Greetings
> Curse187

Hi,

This issue is fixed. Thank you .

**Comment by SimonTheCoder** [comment]
> Hello Simon
> 
> do you plan on adding more features to this trainer?
> Also if you do plan on supporting this game with said trainer, id like to donate some towards you :)
> for the work you have put in so far.
> 
> Regards sal.

Hi,
Yeah, I am still trying to add new fun features.
Thank you for your attention.
